spring.application.name=golf-course-api

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/golfclub}
spring.datasource.username=${DB_USERNAME:golfadmin}
spring.datasource.password=${DB_PASSWORD:golfpassword}

spring.jpa.hibernate.ddl-auto=${DDL_AUTO:create-drop}
spring.jpa.show-sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jackson.serialization.write-dates-as-timestamps=false
